### ISSUE TITLE
Add regex support

### ISSUE THREAD

**Issue by dimitarvdimitrov** [getapid/apid#102]
Fields in the expect block should support regex as well.

This would require either creating a new template syntax for regex (similar to `{{ }}` and `{% %}`) or another optional field on each of the validation fields:

```yaml
expect:
    code:
        regex: '2[0-9]{2}' # any HTTP 2xx status would be accepted 
```

Open to suggestions

**Comment by romaia** [comment]
Supporting regex would be really nice, but I would like to propose a different approach:

I currently have this test:

```yaml
          expect:    
            code: 500
            body:
              - keys_only: true
                is: |
                  {
                    "error": "",
                    "exception": "",
                    "timestamp": "",
                    "traceback_hash": ""
                  }
              - selector: "exception"
                is: "AssertionError: Sale already saved\n"
              - selector: "error"
                is: "bad request!"
```

Where error and exception are hardcoded expected values, while timestamp and traceback_hash would vary from each request.

I would like that this test could be written (something) like this:

```yaml
          expect:    
            code: {/ 5[0-9]{2} /}
            body:
                is: |
                  {
                    "error": "bad request!",
                    "exception": "AssertionError: Sale already saved\n",
                    "timestamp": "{/ [0-9]{4}-[0-9]{2}-[0-9]{2} ... /}",
                    "traceback_hash": "{/ [a-z0-9-]{32} /}"
                  }
```

**Comment by iv-p** [comment]
I do agree this will be a nice addition! 

Unfortunately I don't see how this can be done in this way easily:
```yaml
expect:    
  code: {/ 5[0-9]{2} /}
  body:
      is: |
        {
          "error": "bad request!",
          "exception": "AssertionError: Sale already saved\n",
          "timestamp": "{/ [0-9]{4}-[0-9]{2}-[0-9]{2} ... /}",
          "traceback_hash": "{/ [a-z0-9-]{32} /}"
        }
```

The more I think of it the more I feel like an approach like the one below makes it easier in code and easier to understand as well:
```yaml
expect:    
  code: 5[0-9]{2} # this can be a regex by default
  body:
    - selector: timestamp
      regex: /[0-9]{4}-[0-9]{2}-[0-9]{2}/g
    - selector: traceback_hash
      regex: /[a-z0-9-]{32}/g
    - selector: error
      is: "bad request!"
    - selector: another_key
      is: something # you `can` (but probably shouldn't) use both at the same time
      regex: /\w+/g
``` 

I'll try to draft a PR asap :)
