### ISSUE TITLE
Add optional description filed to trans. and step; set constraints on id field

### ISSUE THREAD

**Issue by dimitarvdimitrov** [getapid/apid#106]
#### Request for comments

Remove `id` field on transactions and steps. Have transactions and steps be mappings instead of lists:

```yaml
transactions:
  authenticated-transaction:
    steps:
      auth:
        variables:
          auth: "am9obi5kb2U6UGE1NXdvcmQ="
        request:
          method: POST
          endpoint: "{{ var.api_url }}/auth"
          headers:
            Authorization: "Basic {{ var.auth }}"
        expect:
          code: 200
          exact: false
        export:
          auth_token: "response.body.token"
          test_header: "response.headers.Test"
```
