### ISSUE TITLE
Step interpolation while in matrix doesn't work

### ISSUE THREAD

**Issue by iv-p** [getapid/apid#146]
### Context

When having a matrix for a certain step, the initial interpolation is successful, but any succeeding ones fail due to them interpolating the already interpolated step.

### To reproduce

Look at the beer test and try to interpolate the `beer_id` in the body

### Expected behavior

The body of the step gets interpolated with the correct data.

### Observed behavior

The body of the step kept the interpolation data from the initial step (didn't interpolate with the next step's data)

### YAML

```yaml
transactions:
  - id: authenticated-transaction
    matrix:
      beer_id: [1, 2]
    steps:
      - id: auth
        variables:
          credentials: "am9obi5kb2U6UGE1NXdvcmQ="
        request:
          method: POST
          endpoint: "{{ var.api.url }}/auth"
          headers:
            Authorization: "Basic {% echo $VAR_CREDENTIALS %}"
        expect:
          code: 200
          exact: false
        export:
          auth_token: "response.body.token"
          test_header: "response.headers.Test"

      - id: get-beer-1
        request:
          method: GET
          endpoint: "{{ var.api.url }}/beer/{{ var.beer_id }}"
          headers:
            Authorization: "Bearer {{ auth.auth_token }}"
        expect:
          code: 200
          body:
            exact: false
            type: json
            content: |
              {
                "beer": {
                  "id": {{ var.beer_id }},
                  "name": "",
                  "type": "",
                  "price": 0
                }
              }
```

In the above example, the `get-beer-1` step will run twice, once for `var.beer_id` 1 and once for 2.

In this example when `var.beer_id` is 2 the expected body should be with id 2, but instead is:
```json
              {
                "beer": {
                  "id": 1,
                  "name": "",
                  "type": "",
                  "price": 0
                }
              }
```

**Comment by dimitarvdimitrov** [comment]
Works for me. Here is the suite and the verbose logs. You can see the URL for `/beer/{id}` change with each run of the tx
<details><summary>suite</summary>

```yaml
---
version: 1
variables:
  api:
    url: http://localhost:80
    abc: 123 # this makes yaml unmarshalling return map[interface{}]interface{}, so it's here just to trigger that
transactions:
  - id: authenticated-transaction
    matrix:
      beer_id: [1, 2]
    steps:
      - id: auth
        variables:
          credentials: "am9obi5kb2U6UGE1NXdvcmQ="
        request:
          method: POST
          endpoint: "{{ var.api.url }}/auth"
          headers:
            Authorization: "Basic {% echo $VAR_CREDENTIALS %}"
        expect:
          code: 200
          exact: false
        export:
          auth_token: "response.body.token"
          test_header: "response.headers.Test"

      - id: get-beers
        request:
          method: GET
          endpoint: "{{ var.api.url }}/beer"
          headers:
            Authorization: "Bearer {{ auth.auth_token }}"
            Test: "{{ auth.test_header }}"
        expect:
          code: 200
          exact: false
          type: json
          content: |
            {
              "beers": [
                {
                  "id": 0,
                  "name": "",
                  "type": "",
                  "price": 0
                }
              ]
            }

      - id: get-beer-1
        request:
          method: GET
          endpoint: "{{ var.api.url }}/beer/{{ var.beer_id }}"
          headers:
            Authorization: "Bearer {{ auth.auth_token }}"
        expect:
          code: 200
          body:
            exact: false
            type: json
            content: |
              {
                "beer": {
                  "id": 0,
                  "name": "",
                  "type": "",
                  "price": 0
                }
              }
```

</details>

<details><summary>logs</summary>
```text
Wed Jul  1 12:46:01 2020        DEBUG   executing request       {"method": "POST", "endpoint": "http://localhost:80/auth", "headers": {"Authorization":["Basic am9obi5kb2U6UGE1NXdvcmQ="]}, "body": ""}
Wed Jul  1 12:46:01 2020        DEBUG   received response       {"endpoint": "http://localhost:80/auth", "method": "POST", "body": "{\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c\"}", "headers": {"Content-Length":["167"],"Content-Type":["application/json; charset=utf-8"],"Date":["Wed, 01 Jul 2020 09:46:01 GMT"],"Test":["test123"]}}
Wed Jul  1 12:46:01 2020        DEBUG   executing request       {"method": "GET", "endpoint": "http://localhost:80/beer", "headers": {"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"],"Test":["test123"]}, "body": ""}
Wed Jul  1 12:46:01 2020        DEBUG   received response       {"endpoint": "http://localhost:80/beer", "method": "GET", "body": "{\"beers\":[{\"id\":1,\"name\":\"Stella Artois\",\"type\":\"pilsner\",\"price\":2.5},{\"id\":2,\"name\":\"Guinness\",\"type\":\"Irish dry stout\",\"price\":3.5},{\"id\":3,\"name\":\"Zagorka\",\"type\":\"lager\",\"price\":1.5}]}", "headers": {"Content-Length":["189"],"Content-Type":["application/json; charset=utf-8"],"Date":["Wed, 01 Jul 2020 09:46:01 GMT"]}}
Wed Jul  1 12:46:01 2020        DEBUG   executing request       {"method": "GET", "endpoint": "http://localhost:80/beer/1", "headers": {"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"]}, "body": ""}
Wed Jul  1 12:46:01 2020        DEBUG   received response       {"endpoint": "http://localhost:80/beer/1", "method": "GET", "body": "{\"beer\":{\"id\":1,\"name\":\"Stella Artois\",\"type\":\"pilsner\",\"price\":2.5}}", "headers": {"Content-Length":["69"],"Content-Type":["application/json; charset=utf-8"],"Date":["Wed, 01 Jul 2020 09:46:01 GMT"]}}
authenticated-transaction-1:
    OK   auth
    OK   get-beers
    OK   get-beer-1
Wed Jul  1 12:46:01 2020        DEBUG   executing request       {"method": "POST", "endpoint": "http://localhost:80/auth", "headers": {"Authorization":["Basic am9obi5kb2U6UGE1NXdvcmQ="]}, "body": ""}
Wed Jul  1 12:46:01 2020        DEBUG   received response       {"endpoint": "http://localhost:80/auth", "method": "POST", "body": "{\"token\":\"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c\"}", "headers": {"Content-Length":["167"],"Content-Type":["application/json; charset=utf-8"],"Date":["Wed, 01 Jul 2020 09:46:01 GMT"],"Test":["test123"]}}
Wed Jul  1 12:46:01 2020        DEBUG   executing request       {"method": "GET", "endpoint": "http://localhost:80/beer", "headers": {"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"],"Test":["test123"]}, "body": ""}
Wed Jul  1 12:46:01 2020        DEBUG   received response       {"endpoint": "http://localhost:80/beer", "method": "GET", "body": "{\"beers\":[{\"id\":1,\"name\":\"Stella Artois\",\"type\":\"pilsner\",\"price\":2.5},{\"id\":2,\"name\":\"Guinness\",\"type\":\"Irish dry stout\",\"price\":3.5},{\"id\":3,\"name\":\"Zagorka\",\"type\":\"lager\",\"price\":1.5}]}", "headers": {"Content-Length":["189"],"Content-Type":["application/json; charset=utf-8"],"Date":["Wed, 01 Jul 2020 09:46:01 GMT"]}}
Wed Jul  1 12:46:01 2020        DEBUG   executing request       {"method": "GET", "endpoint": "http://localhost:80/beer/2", "headers": {"Authorization":["Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c"]}, "body": ""}
Wed Jul  1 12:46:01 2020        DEBUG   received response       {"endpoint": "http://localhost:80/beer/2", "method": "GET", "body": "{\"beer\":{\"id\":2,\"name\":\"Guinness\",\"type\":\"Irish dry stout\",\"price\":3.5}}", "headers": {"Content-Length":["72"],"Content-Type":["application/json; charset=utf-8"],"Date":["Wed, 01 Jul 2020 09:46:01 GMT"]}}
authenticated-transaction-2:
    OK   auth
    OK   get-beers
    OK   get-beer-1
```
</details>

Templating the response with an `exact: false` won't change the success of the suite, if that's what you were looking for
